version: '3.8'

services:
  fastapi-snowflake:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./keys:/app/keys:ro
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload